name: vllm-yourname

services:
  vllm:
    container_name: vllm-yourname
    build: .
    image: vllm-phos:yourname
    pull_policy: build
    init: true # handle stop signals
    # runtime: nvidia
    # cpuset: "1,3,5,7,9,11" # nvidia-smi topo -m
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              # device_ids: ["0"]
    # environment:
    #   - VLLM_USE_MODELSCOPE=True
    devices:
      - /dev/infiniband
    network_mode: host # for TCP and RDMA handshake
    shm_size: 256GB # for SHM channel; not using "ipc: host" for namespace isolation
    ulimits:
      memlock: -1 # unlimited pinned memory
      stack: 67108864
    volumes:
      - ../..:/workspace
      # - /path/to/docker-root:/root # this shadows Rust installation in the image
    # Uncomment to use CRIU
    # privileged: true
