#include "cublasLt.h"

#if CUBLAS_VER_MAJOR >= 12
#if defined(__cplusplus)
extern "C" {
#endif
void cublasLtACCMatmul();
void cublasLtACCMatmulAlgoCapGetAttribute();
void cublasLtACCMatmulAlgoCheck();
void cublasLtACCMatmulAlgoGetHeuristic();
void cublasLtACCMatmulAlgoGetIds();
void cublasLtACCMatmulAlgoInit();
void cublasLtAlgoCharacteristicGetAttribute();
void cublasLtBIIMatmul();
void cublasLtBIIMatmulAlgoCapGetAttribute();
void cublasLtBIIMatmulAlgoCheck();
void cublasLtBIIMatmulAlgoGetHeuristic();
void cublasLtBIIMatmulAlgoGetIds();
void cublasLtBIIMatmulAlgoInit();
void cublasLtBSBMatmul();
void cublasLtBSBMatmulAlgoCapGetAttribute();
void cublasLtBSBMatmulAlgoCheck();
void cublasLtBSBMatmulAlgoGetHeuristic();
void cublasLtBSBMatmulAlgoGetIds();
void cublasLtBSBMatmulAlgoInit();
void cublasLtBSSMatmul();
void cublasLtBSSMatmulAlgoCapGetAttribute();
void cublasLtBSSMatmulAlgoCheck();
void cublasLtBSSMatmulAlgoGetHeuristic();
void cublasLtBSSMatmulAlgoGetIds();
void cublasLtBSSMatmulAlgoInit();
void cublasLtCCCMatmul();
void cublasLtCCCMatmulAlgoCapGetAttribute();
void cublasLtCCCMatmulAlgoCheck();
void cublasLtCCCMatmulAlgoGetHeuristic();
void cublasLtCCCMatmulAlgoGetIds();
void cublasLtCCCMatmulAlgoInit();
void cublasLtClearNvjetCache();
void cublasLtCtxInit();
void cublasLtDDDMatmul();
void cublasLtDDDMatmulAlgoCapGetAttribute();
void cublasLtDDDMatmulAlgoCheck();
void cublasLtDDDMatmulAlgoGetHeuristic();
void cublasLtDDDMatmulAlgoGetIds();
void cublasLtDDDMatmulAlgoInit();
void cublasLtGetEnvironmentMode();
void cublasLtHHHMatmul();
void cublasLtHHHMatmulAlgoCapGetAttribute();
void cublasLtHHHMatmulAlgoCheck();
void cublasLtHHHMatmulAlgoGetHeuristic();
void cublasLtHHHMatmulAlgoGetIds();
void cublasLtHHHMatmulAlgoInit();
void cublasLtHSHMatmul();
void cublasLtHSHMatmulAlgoCapGetAttribute();
void cublasLtHSHMatmulAlgoCheck();
void cublasLtHSHMatmulAlgoGetHeuristic();
void cublasLtHSHMatmulAlgoGetIds();
void cublasLtHSHMatmulAlgoInit();
void cublasLtHSSMatmul();
void cublasLtHSSMatmulAlgoCapGetAttribute();
void cublasLtHSSMatmulAlgoCheck();
void cublasLtHSSMatmulAlgoGetHeuristic();
void cublasLtHSSMatmulAlgoGetIds();
void cublasLtHSSMatmulAlgoInit();
void cublasLtHeuristicLutSerializeEntry();
void cublasLtKCCMatmul();
void cublasLtKCCMatmulAlgoCapGetAttribute();
void cublasLtKCCMatmulAlgoCheck();
void cublasLtKCCMatmulAlgoGetHeuristic();
void cublasLtKCCMatmulAlgoGetIds();
void cublasLtKCCMatmulAlgoInit();
void cublasLtKCKMatmul();
void cublasLtKCKMatmulAlgoCapGetAttribute();
void cublasLtKCKMatmulAlgoCheck();
void cublasLtKCKMatmulAlgoGetHeuristic();
void cublasLtKCKMatmulAlgoGetIds();
void cublasLtKCKMatmulAlgoInit();
void cublasLtLegacyGemmACC();
void cublasLtLegacyGemmBII();
void cublasLtLegacyGemmBSS();
void cublasLtLegacyGemmCCC();
void cublasLtLegacyGemmDDD();
void cublasLtLegacyGemmHHH();
void cublasLtLegacyGemmHSH();
void cublasLtLegacyGemmHSS();
void cublasLtLegacyGemmSSS();
void cublasLtLegacyGemmTSS();
void cublasLtLegacyGemmTST();
void cublasLtLegacyGemmUtilizationCCC();
void cublasLtLegacyGemmUtilizationDDD();
void cublasLtLegacyGemmUtilizationZZZ();
void cublasLtLegacyGemmZZZ();
void cublasLtMatmulAlgoConfigGetAttributeRange();
void cublasLtSSSMatmul();
void cublasLtSSSMatmulAlgoCapGetAttribute();
void cublasLtSSSMatmulAlgoCheck();
void cublasLtSSSMatmulAlgoGetHeuristic();
void cublasLtSSSMatmulAlgoGetIds();
void cublasLtSSSMatmulAlgoInit();
void cublasLtSetEnvironmentMode();
void cublasLtShutdownCtx();
void cublasLtTSSMatmul();
void cublasLtTSSMatmulAlgoCapGetAttribute();
void cublasLtTSSMatmulAlgoCheck();
void cublasLtTSSMatmulAlgoGetHeuristic();
void cublasLtTSSMatmulAlgoGetIds();
void cublasLtTSSMatmulAlgoInit();
void cublasLtTSTMatmul();
void cublasLtTSTMatmulAlgoCapGetAttribute();
void cublasLtTSTMatmulAlgoCheck();
void cublasLtTSTMatmulAlgoGetHeuristic();
void cublasLtTSTMatmulAlgoGetIds();
void cublasLtTSTMatmulAlgoInit();
void cublasLtVCCMatmul();
void cublasLtVCCMatmulAlgoCapGetAttribute();
void cublasLtVCCMatmulAlgoCheck();
void cublasLtVCCMatmulAlgoGetHeuristic();
void cublasLtVCCMatmulAlgoGetIds();
void cublasLtVCCMatmulAlgoInit();
void cublasLtVCVMatmul();
void cublasLtVCVMatmulAlgoCapGetAttribute();
void cublasLtVCVMatmulAlgoCheck();
void cublasLtVCVMatmulAlgoGetHeuristic();
void cublasLtVCVMatmulAlgoGetIds();
void cublasLtVCVMatmulAlgoInit();
void cublasLtZZZMatmul();
void cublasLtZZZMatmulAlgoCapGetAttribute();
void cublasLtZZZMatmulAlgoCheck();
void cublasLtZZZMatmulAlgoGetHeuristic();
void cublasLtZZZMatmulAlgoGetIds();
void cublasLtZZZMatmulAlgoInit();
void cublasLt_for_cublas_BII();
void cublasLt_for_cublas_BSS();
void cublasLt_for_cublas_CCC();
void cublasLt_for_cublas_DDD();
void cublasLt_for_cublas_HHH();
void cublasLt_for_cublas_HSH();
void cublasLt_for_cublas_HSS();
void cublasLt_for_cublas_SSS();
void cublasLt_for_cublas_TSS();
void cublasLt_for_cublas_TST();
void cublasLt_for_cublas_ZZZ();
#if defined(__cplusplus)
}
#endif
#endif

#if CUBLAS_VER_MAJOR >= 13
#if defined(__cplusplus)
extern "C" {
#endif
void cublasLtHeuristicsCacheCreate();
void cublasLtHeuristicsCacheDestroy();
void cublasLtHeuristicsCacheGet();
void cublasLtHeuristicsCachePut();
#if defined(__cplusplus)
}
#endif
#endif
